- name: Install dependencies
  yum:
    name:
      - curl
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
    state: present

- name: Add Kubernetes YUM repository
  yum_repository:
    name: kubernetes
    description: Kubernetes
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-$basearch
    enabled: yes
    gpgcheck: 1
    repo_gpgcheck: 1
    gpgkey:
      - https://packages.cloud.google.com/yum/doc/yum-key.gpg
      - https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    exclude: kubelet kubeadm kubectl

## Exluding  kubelet kubeadm kubectl everytime as part of yum update 

- name: Install Kubernetes packages
  yum:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present
    disable_excludes: kubernetes

- name: Enable and start kubelet
  systemd:
    name: kubelet
    enabled: yes
    state: started

- name: Disable swap
  shell: |
    swapoff -a
    sed -i '/ swap / s/^/#/' /etc/fstab
  args:
    warn: false

    
## Other tasks can be added here as needed