apiVersion: v2
name: apps-deployment-engine
description: a Application deployment Engine .
version: 0.2.0 
appVersion: "1.0.0" 
keywords:
  - deployment
  - service
  - ingress
maintainers:
  - name: Your Name
    email: your.email@example.com