apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.service.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "postgres-chart.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "postgres-chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: {{ .Values.global.service.port }}
      targetPort: {{ .Values.global.service.targetPort }}
  clusterIP: None 