apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres-chart.fullname" . }}-secret # Using fullname for secret name consistency
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "postgres-chart.labels" . | nindent 4 }}
  {{- if .Values.global.vault.enabled }}
  annotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/agent-inject-secret-password: "{{ .Values.global.vault.path }}"
    {{- if .Values.global.replication.enabled }}
    vault.hashicorp.com/agent-inject-secret-replication-password: "{{ .Values.global.vault.replicationPath }}"
    {{- end }}
    vault.hashicorp.com/role: "{{ .Values.global.vault.role }}"
    # Add other Vault annotations as needed, e.g., vault.hashicorp.com/agent-inject-template-<secret-key>: |
  {{- end }}
type: Opaque # Secrets managed by Vault Agent Injector should be Opaque or kubernetes.io/tls etc.